import{a as f,S as m,i}from"./assets/vendor--6n4cVRZ.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const y=async(e,s)=>{const a="54567653-327de5fba17dc16d91ee3d6a6",r="https://pixabay.com/api/";try{return(await f.get(r,{params:{key:a,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}catch(t){throw console.error("Error fetching images:",t),t}};let h=new m(".gallery a",{captionsData:"alt",captionDelay:250});function p(e){const s=document.querySelector(".gallery"),a=e.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <ul class="info">
          <li class="info-item"><b>Likes</b> <span>${r.likes}</span></li>
          <li class="info-item"><b>Views</b> <span>${r.views}</span></li>
          <li class="info-item"><b>Comments</b> <span>${r.comments}</span></li>
          <li class="info-item"><b>Downloads</b> <span>${r.downloads}</span></li>
        </ul>
      </li>`).join("");s.insertAdjacentHTML("beforeend",a),h.refresh()}function g(){const e=document.querySelector(".loader");e&&e.classList.remove("is-hidden")}function b(){const e=document.querySelector(".loader");e&&e.classList.add("is-hidden")}function L(){const e=document.querySelector(".load-more");e&&e.classList.remove("is-hidden")}function d(){const e=document.querySelector(".load-more");e&&e.classList.add("is-hidden")}function w(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}let c="",n=1,q=0;const S=document.querySelector(".form"),v=document.querySelector(".load-more");S.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.currentTarget.elements["search-text"].value.trim(),!c){i.warning({message:"Please enter a search query"});return}n=1,w(),d(),await u(),e.target.reset()});v.addEventListener("click",async()=>{n+=1,await u()});async function u(){g();try{const e=await y(c,n);if(q=e.totalHits,e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}if(p(e.hits),n*15<e.totalHits?L():(d(),n>1&&i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),n>1){const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch(e){i.error({message:"Error fetching data. Try again!"}),console.error(e)}finally{b()}}
//# sourceMappingURL=index.js.map
